TimeMgmtWebApp/Controllers/ModuleController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TimeMgmtLibraryCore.DataAccess;
using TimeMgmtLibraryCore.Models;

namespace TimeMgmt.Controllers
{
    public class ModuleController : Controller
    {
        //GET: ModuleDAL
        //Creating an object of the ModuleDAL
        public ModuleDAL moduleDAL = new ModuleDAL();

        public ViewResult Index()
        {
            //Get all User Modules
            var moduleList = new List<ModuleModel>();
            //Calling the DAL method which parses a list with all the users modules.
            moduleList = moduleDAL.GetUserModules().ToList();
            //Return the list of modules for the logged in user to the Modules view.
            return View(moduleList);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Add([Bind] ModuleModel moduleObj)
        {
            if (ModelState.IsValid)
            {
                //Calling the DAL method to add a new module for the user.
                moduleDAL.AddNewModule(moduleObj);
                //once the module is added redirect to the Index view.
                return RedirectToAction("Index");
            }
            return View(moduleObj);
        }

    }
}

TimeMgmtWebApp/Controllers/SemesterController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TimeMgmtLibraryCore.DataAccess;
using TimeMgmtLibraryCore.Models;

namespace TimeMgmt.Controllers
{
    public class SemesterController : Controller
    {
        //Creating an object of the SemesterDAL
        SemesterDAL semesterDAL = new SemesterDAL();

        public IActionResult Index()
        {
            //Using the DAL to retrieve the users semester data.
            SemesterModel semester = semesterDAL.GetUserSemester();
            return View(semester);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind] SemesterModel semesterObj)
        {
            if (ModelState.IsValid)
            {
                //Calling the DAL method to create a new semester and remove all this semesters data.
                semesterDAL.CreateNewSemester(semesterObj);
                return RedirectToAction("Index");
            }
            return View(semesterObj);
        }

    }
}

TimeMgmtWebApp/Controllers/WeekController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TimeMgmtLibraryCore.DataAccess;
using TimeMgmtLibraryCore.Models;

namespace TimeMgmtWebApp.Controllers
{
    public class WeekController : Controller
    {
        //GET: WeekDAL
        //Creating an object of the ModuleDAL
        public WeekDAL weekDAL = new WeekDAL();
        public ViewResult Index()
        {
            //Get all User Modules
            var weekModuleList = new List<UserModule>();
            weekModuleList = weekDAL.GetUserWeekModules().ToList();
            //Return the list of modules for the logged in user to the Modules view.
            return View(weekModuleList);
        }

        [HttpGet]
        [Route("Week/Record/{moduleCode}")]
        public IActionResult Record(string moduleCode)
        {
            if (moduleCode == null)
            {
                return NotFound();
            }

            UserModule um = weekDAL.GetUserModuleByModuleCode(moduleCode);

            if (um == null)
            {
                return NotFound();
            }

            return View(um);
        }

        [Route("Week/Record/{moduleCode}")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Record(string moduleCode, [Bind] UserModule userModuleObj)
        {
            if (moduleCode == null)
            {
                return NotFound();
            }
            //Calling the DAL method to check if the module exists.
            if (weekDAL.SearchForModule(userModuleObj).Equals(true))
            {
                //Calling the DAL method to update the self study hours for the module specified.
                weekDAL.updateSelfStudyHrs(userModuleObj);
                return RedirectToAction("Index");
            }
            //if the module does not exist display the error view.
            else if (weekDAL.SearchForModule(userModuleObj).Equals(false))
            {
                return RedirectToAction("ModuleCodeError");
            }

            return View(userModuleObj);
        }

        [HttpGet]
        [Route("Week/Reminder/{moduleCode}")]
        public IActionResult Reminder(string moduleCode)
        {
            if (moduleCode == null)
            {
                return NotFound();
            }
            UserModule um = weekDAL.GetUserModuleByModuleCode(moduleCode);

            if (um == null)
            {
                return NotFound();
            }

            return View(um);
        }

        [Route("Week/Reminder/{moduleCode}")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Reminder(string moduleCode, [Bind] UserModule userModuleObj)
        {
            if (moduleCode == null)
            {
                return NotFound();
            }

            if (weekDAL.SearchForModule(userModuleObj).Equals(true))
            {
                weekDAL.SetModuleReminder(userModuleObj);
                return RedirectToAction("Index");
            }
            else if (weekDAL.SearchForModule(userModuleObj).Equals(false))
            {
                return RedirectToAction("ModuleCodeError");
            }

            return View(userModuleObj);
        }

        public IActionResult ModuleCodeError()
        {
            return View();
        }

    }
}

TimeMgmtWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TimeMgmtWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-morph.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-primary border-bottom box-shadow mb-3">
            <div class="container">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <div class="navbar-nav mx-auto">
                        <ul class="navbar-nav flex-grow-1">
                            @if (TimeMgmtLibraryCore.DataAccess.UserDAL.uDAL.GetLoggedInUser() != null)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Semester" asp-action="Index">My Semester</a>
                                </li>
                                @if (TimeMgmtLibraryCore.DataAccess.SemesterDAL.getDbNumOfWeeks() > 0)
                                {
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Module" asp-action="Index">My Modules</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Week" asp-action="Index">My Week</a>
                                    </li>
                                }
                            }
                        </ul>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023  - TimeMgmtWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>